[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/p/*"
  to = "/.netlify/functions/profile?slug=:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/register"
  to = "/register.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
